export default [
  { componentName: "X", enable: true },
  { componentName: "Bluesky", enable: false },
  { componentName: "Threads", enable: false },
  { componentName: "Mastodon", enable: false },
  { componentName: "Facebook", enable: true },
  { componentName: "Pocket", enable: true },
  { componentName: "LINE", enable: true },
  { componentName: "Pinterest", enable: false },
  { componentName: "LinkedIn", enable: false },
  { componentName: "Hatebu", enable: true },
  { componentName: "Gmail", enable: false },
  { componentName: "Email", enable: false },
  { componentName: "Tumblr", enable: false },
  { componentName: "Note", enable: true },
  { componentName: "Feedly", enable: false },
  { componentName: "WaybackMachine", enable: true },
  { componentName: "CopyTitle", enable: false },
  { componentName: "CopyTitleUrl", enable: true },
  { componentName: "CopyLinkAsHtml", enable: false },
  { componentName: "CopyLinkAsMd", enable: false },
  { componentName: "CopyLinkAsRichText", enable: true },
  { componentName: "QR", enable: true },
  { componentName: "AmazonShorter", enable: true },
  { componentName: "Print", enable: false },
  { componentName: "Other", enable: true },
]
